(function(){var a=Handlebars.template,b=Handlebars.templates=Handlebars.templates||{};b["task_list.hbs"]=a(function(a,b,c,d,e){function m(a,b){var d="",e;d+='\n  <section id="main">\n    <ul id="todo-list">\n      ',e=c.each.call(a,a.tasks,{hash:{},inverse:k.noop,fn:k.program(2,n,b),data:b});if(e||e===0)d+=e;return d+="\n    </ul>\n  </section>\n",d}function n(a,b){var d="",e,f;return d+="\n        ",f={hash:{task:a},data:b},d+=j((e=c.subView,e?e.call(a,"TaskItemView",f):i.call(a,"subView","TaskItemView",f)))+"\n      ",d}this.compilerInfo=[2,">= 1.0.0-rc.3"],c=c||a.helpers,e=e||{};var f="",g,h,i=c.helperMissing,j=this.escapeExpression,k=this,l="function";f+='<header id="header">\n  <input id="new-todo" placeholder="What have you got to do?" autofocus>\n</header>\n\n',h=c["if"].call(b,(g=b.tasks,g==null||g===!1?g:g.length),{hash:{},inverse:k.noop,fn:k.program(1,m,e),data:e});if(h||h===0)f+=h;return f+='\n\n<footer id="footer">\n  <span id="todo-count">',(h=c.remainingCount)?h=h.call(b,{hash:{},data:e}):(h=b.remainingCount,h=typeof h===l?h.apply(b):h),f+=j(h)+' left</span>\n\n  <ul id="filters">\n    <li>\n      <a href="#">All</a>\n    </li>\n    <li>\n      <a href="#">Active</a>\n    </li>\n    <li>\n      <a href="#">Completed</a>\n    </li>\n  </ul>\n\n  <button id="clear-completed">Clear completed (',(h=c.completedCount)?h=h.call(b,{hash:{},data:e}):(h=b.completedCount,h=typeof h===l?h.apply(b):h),f+=j(h)+")</button>\n</footer>\n",f}),b["task_item.hbs"]=a(function(a,b,c,d,e){function l(a,b){return"checked"}this.compilerInfo=[2,">= 1.0.0-rc.3"],c=c||a.helpers,e=e||{};var f="",g,h,i=this,j="function",k=this.escapeExpression;f+='<div class="view">\n  <input class="toggle" type="checkbox" ',h=c["if"].call(b,(g=b.task,g==null||g===!1?g:g.completed),{hash:{},inverse:i.noop,fn:i.program(1,l,e),data:e});if(h||h===0)f+=h;return f+=">\n  <label>"+k((g=(g=b.task,g==null||g===!1?g:g.name),typeof g===j?g.apply(b):g))+'</label>\n  <button class="destroy"></button>\n</div>\n',f})})()

;
// Generated by CoffeeScript 1.6.2
(function() {
  var _base, _base1, _base2, _base3, _ref, _ref1, _ref2, _ref3,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  (_base = window.Backbone).Models || (_base.Models = {});

  window.Backbone.Models.Task = (function(_super) {
    __extends(Task, _super);

    function Task() {
      _ref = Task.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Task.prototype.defaults = {
      title: '',
      completed: false
    };

    Task.prototype.toggle = function() {
      this.set('completed', !this.get('completed'));
      return this.save();
    };

    return Task;

  })(Backbone.Model);

  window.Backbone || (window.Backbone = {});

  (_base1 = window.Backbone).Collections || (_base1.Collections = {});

  Backbone.Collections.TaskCollection = (function(_super) {
    __extends(TaskCollection, _super);

    function TaskCollection() {
      _ref1 = TaskCollection.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    TaskCollection.prototype.localStorage = new Backbone.LocalStorage("SomeCollection");

    TaskCollection.prototype.model = Backbone.Models.Task;

    TaskCollection.prototype.clearCompleted = function() {
      return this.reset(this.active());
    };

    TaskCollection.prototype.byStatus = function(status) {
      if (status !== "all") {
        if (this[status] != null) {
          return this[status]();
        }
      }
      return this.models;
    };

    TaskCollection.prototype.completed = function() {
      return this.filter(function(todo) {
        return todo.get('completed');
      });
    };

    TaskCollection.prototype.active = function() {
      return this.without.apply(this, this.completed());
    };

    return TaskCollection;

  })(Backbone.Collection);

  window.Backbone || (window.Backbone = {});

  (_base2 = window.Backbone).Views || (_base2.Views = {});

  Backbone.Views.TaskListView = (function(_super) {
    __extends(TaskListView, _super);

    function TaskListView() {
      this.render = __bind(this.render, this);
      this.completedCount = __bind(this.completedCount, this);
      this.remainingCount = __bind(this.remainingCount, this);      _ref2 = TaskListView.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    TaskListView.prototype.template = Handlebars.templates['task_list.hbs'];

    TaskListView.prototype.events = {
      'keypress #new-todo': 'addOnEnter',
      'click #filters a': 'setFilter',
      'click #clear-completed': 'clearCompleted'
    };

    TaskListView.prototype.initialize = function(options) {
      Handlebars.registerHelper('remainingCount', this.remainingCount);
      Handlebars.registerHelper('completedCount', this.completedCount);
      this.tasks = new Backbone.Collections.TaskCollection();
      this.tasks.on('change', this.render);
      this.tasks.on('destroy', this.render);
      this.tasks.on('reset', this.render);
      return this.render();
    };

    TaskListView.prototype.addOnEnter = function(event) {
      if (event.which === 13) {
        return this.addTask();
      }
    };

    TaskListView.prototype.addTask = function() {
      var name, task;

      name = $('#new-todo').val().trim();
      if (name.length > 0) {
        task = new Backbone.Models.Task();
        task.set('name', name);
        this.tasks.add(task);
        return this.render();
      }
    };

    TaskListView.prototype.setFilter = function(event) {
      this.filter = $(event.target).text().toLowerCase();
      return this.render();
    };

    TaskListView.prototype.clearCompleted = function() {
      return this.tasks.clearCompleted();
    };

    TaskListView.prototype.remainingCount = function() {
      var count, word;

      count = this.tasks.active().length;
      word = "items";
      if (count === 1) {
        word = "item";
      }
      return new Handlebars.SafeString("" + count + " " + word);
    };

    TaskListView.prototype.completedCount = function() {
      return this.tasks.completed().length;
    };

    TaskListView.prototype.render = function() {
      var tasks;

      tasks = this.tasks.models;
      if (this.filter != null) {
        tasks = this.tasks.byStatus(this.filter);
      }
      this.closeSubViews();
      this.$el.html(this.template({
        tasks: tasks
      }));
      this.renderSubViews();
      return this;
    };

    TaskListView.prototype.onClose = function() {
      return this.closeSubViews();
    };

    return TaskListView;

  })(Backbone.Diorama.NestingView);

  window.Backbone || (window.Backbone = {});

  (_base3 = window.Backbone).Views || (_base3.Views = {});

  Backbone.Views.TaskItemView = (function(_super) {
    __extends(TaskItemView, _super);

    function TaskItemView() {
      this.setCompleted = __bind(this.setCompleted, this);
      this.remove = __bind(this.remove, this);
      this.render = __bind(this.render, this);      _ref3 = TaskItemView.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    TaskItemView.prototype.template = Handlebars.templates['task_item.hbs'];

    TaskItemView.prototype.tagName = 'li';

    TaskItemView.prototype.events = {
      "click input": "setCompleted",
      "click .destroy": "clear"
    };

    TaskItemView.prototype.initialize = function(options) {
      this.model = options.task;
      this.model.on('change', this.render);
      this.model.on('destroy', this.remove);
      return this.render();
    };

    TaskItemView.prototype.render = function() {
      this.$el.html(this.template({
        task: this.model.toJSON()
      }));
      if (this.model.get('completed')) {
        this.$el.attr('class', 'completed');
      }
      return this;
    };

    TaskItemView.prototype.remove = function() {
      this.$el.remove();
      return this.stopListening();
    };

    TaskItemView.prototype.clear = function() {
      return this.model.destroy();
    };

    TaskItemView.prototype.setCompleted = function(event) {
      var isChecked;

      isChecked = $(event.target).is(":checked");
      return this.model.set('completed', isChecked);
    };

    TaskItemView.prototype.onClose = function() {
      return this.model.off('change', this.render);
    };

    return TaskItemView;

  })(Backbone.View);

}).call(this);
